### ISSUE TITLE
[TF1] more videos, date, videos duration

### ISSUE THREAD

**Issue by SylvainCecchetto** [SylvainCecchetto/plugin.video.catchuptvandmore#10]
- [x] Add the "More videos" button in case of multiple pages on website
- [x] Add the date of each videos 
- [x] Add the duration of each videos

**Comment by tug912** [comment]
Hello, 

merci pour l'addon, vraiment Top.

J'aimerais juste savoir si il y a un repo "officiel" car j'ai impérativement besoin qu'il puisse se mettre à jour automatiquement vie le repo.

Merci par avance.

**Comment by SylvainCecchetto** [comment]
Salut !
Ben merci à toi de l'utiliser ;-) Je n'ai pas beaucoup de temps à y consacrer mais je fais mon possible !

Il est présent sur le repo officiel de Kodi mais en version 0.1.0 je crois. La dernière version est en cours de soumission, elle devrait bientôt arriver.

Sinon si tu as un Unix tu peux toujours directement faire un script cron pour faire régulièrement un git pull du repo ? Je pense que ça peut le faire ;-)

**Comment by tug912** [comment]
Ok merci je vais regarder ça.

Sinon je vais encore t’embêter mais j'ai un soucis. j'utilise Super Favourites pr faire mon menu kodi et quand je mets un liens en super favoris message d'erreur et il ne veut pas m'y emmener ou quand il y va la video ne se lance pas. Mais quand je passe part CatchUp tout se lance parfaitement.

**Comment by SylvainCecchetto** [comment]
Ah je ne connais pas ce plugin.

Est ce que tu peux ouvrir une issue avec le log au moment de l'erreur stp ?

**Comment by SylvainCecchetto** [comment]
Date and duration missing informations resolved in commit b4f0cff6efe0df4c050c22a6309a3da59c1fe8b7 and 802dc6f24305a9081afee5453c41a5673bfb77bb

**Comment by wwark** [comment]
Add the "More videos" button in case of multiple pages on website in dev branch
