### ISSUE TITLE
Error Contents: 'str' object is not callable sous android 5.1.1

### ISSUE THREAD

**Issue by jeff2900** [SylvainCecchetto/plugin.video.catchuptvandmore#2]
Bonjour,
J'ai voulu tester votre addons, mais malheureusement il ne fonctionne pas sur mon environnement box TV android 5.1.1.

L'addon ne se lance pas ni avec kodi 17.0 ni SPMC 16.5.82

Le message d'erreur est le même:
22:09:16.371` T:18446744072305297632   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'str' object is not callable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 45, in <module>
                                                _ = common.addon.initialize_gettext()
                                            TypeError: 'str' object is not callable
                                            -->End of Python script error report<--
22:09:16.448 T:18446744072288516616   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
22:09:16.450 T:18446744072288516616   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) `failed

En espérant pouvoir utiliser votre addon prochainement.

**Comment by SylvainCecchetto** [comment]
Bonsoir Jeff,

Merci pour se tout premier retour. En effet j'ai aussi eu se problème sur mon Macbook, il s'agit d'une erreur de ma part concernant la dépendance de l'addon simpleplugin.

J'ai normalement corrigé le problème en fin d'après midi un intégrant directement le framework simpleplugin dans mon addon.

Je vous propose de télécharger à nouveau le fichier zip à cette adresse : [https://github.com/SylvainCecchetto/plugin.video.catchuptvandmore/archive/master.zip](https://github.com/SylvainCecchetto/plugin.video.catchuptvandmore/archive/master.zip)

Ne pas oublier de supprimer préalablement l'addon depuis Kodi avant d'installer cette nouvelle version.

N'hésitez pas pour d'autres questions ou suggestions, retour de bugs etc (Je n'ai pas de box Android pour tester sur cette plateforme).

Merci d'avance pour votre retour.

**Comment by jeff2900** [comment]
Merci pour la réponse rapide, mais il y a toujours la même erreur.

Après quelque recherche sur internet il faut aussi mettre à jour l'addon simpleplugin.
J'ai installé la version v2.1.0 depuis l'url https://github.com/romanvm/script.module.simpleplugin/releases
Et à présent le plugin fonctionne.

En espérant que cela aidera d'autre personnes.

**Comment by SylvainCecchetto** [comment]
Oui effectivement c'est bien ça le problème.

Dans mon addon j'utilise une fonctionnalité de simpleplugin qui n'est disponible que dans la version 2.1.0 de simpleplugin, or la dernière version de simpleplugin présente sur les répo de Kodi est la 1.6 je crois.

Du coup dans la version actuelle de mon addon sur GitHub j'ai intégré directement simpleplugin dans mon dossier lib et pour ne plus être dépendent de la version de simpleplugin proposé par Kodi.

Justement ce que je ne comprends pas c'est que même avec le "nouveau" zip vous ayez encore eu ce problème ...

Je me permets de re ouvrir le ticket et demain je vais faire le test avec une install de Kodi clean pour être sur ;-)

Merci du retour !

**Comment by SylvainCecchetto** [comment]
Je viens d'ajouter des nouvelles chaines et j'en ai profité pour tester une installation du plugin depuis le zip en ayant préalablement installé un Kodi clean.

Résultat : je n'ai pas de problème d'installation et pas de problème de lancement de l'addon. Kodi n'installe pas l'addon simpleplugin et mon addon utilise bien le fichier simpleplugin.py présent dans le dossier lib.

Je ferme le ticket en espérant que ça fonctionne pour tout le monde ...
