### ISSUE TITLE
TMC|NT1|HD1 SD stream no 720p

### ISSUE THREAD

**Issue by wwark** [SylvainCecchetto/plugin.video.catchuptvandmore#20]
Hello,

J'ai testé plusieurs cas nous avons que des flux 720p pour TF1 les autres chaines du groupe nous avons que des flux SD.

Le cas de l'emission quotidien sur TMC où sur le site nous avons bien un flux 720p.
Est-ce que des logs sont utiles ?

Merci,

**Comment by SylvainCecchetto** [comment]
Ah je vais regarder, merci

**Comment by SylvainCecchetto** [comment]
J'avais oublié d'ajouter les paramètres dans settings.xml pour ces chaines là, c'est normalement résolu avec les commit 20a5ba80e4e72b14b0ea79d16b903e037d2dc921 et a0c32a7a133b5fe3ecf301f1b999ba3d37a19ef5 dans les 2 branches master et dev.

J'attends confirmation pour fermer l'issue

Merci pour ce retour de bug ! =D

**Comment by wwark** [comment]
ça marche mais il y a deux issue

30091  mettre HD1 dans le strings.po anglais

+msgctxt "#30090"
+msgid "NT1: Video quality"
+msgstr ""
+
+msgctxt "#30091"
+msgid "NT1: Video quality"
+msgstr ""

Et dans le fichier settings.xml 

J'ai remplacé -9 par -19 car NT1 n'apparraissait pas dans la liste des settings.

La bonne valeur ci-dessous
<setting label="NT1" type="bool" id="channels.fr.tf1.nt1" default="true" visible="false"/>
                <setting label="30090" type="labelenum" id="channels.fr.tf1.nt1.quality" visible="eq(-1,true) + eq(-19,true)" values="Force HD|Auto"/>

**Comment by wwark** [comment]
<setting label="NT1" type="bool" id="channels.fr.tf1.nt1" default="true" visible="false"/>
                <setting label="30090" type="labelenum" id="channels.fr.tf1.nt1.quality" visible="eq(-1,true) + eq(-19,true)" values="Force HD|Auto"/>

**Comment by wwark** [comment]
"<setting label="NT1" type="bool" id="channels.fr.tf1.nt1" default="true" visible="false"/>
                <setting label="30090" type="labelenum" id="channels.fr.tf1.nt1.quality" visible="eq(-1,true) + eq(-19,true)" values="Force HD|Auto"/>"

**Comment by wwark** [comment]
setting label="NT1" type="bool" id="channels.fr.tf1.nt1" default="true" visible="false"/>
                <setting label="30090" type="labelenum" id="channels.fr.tf1.nt1.quality" visible="eq(-1,true) + eq(-19,true)" values="Force HD|Auto"

**Comment by SylvainCecchetto** [comment]
Oups oublié de sauvegarder mes fichiers avant de commit -_-'

Merci, je corrige/push ça tout de suite

**Comment by SylvainCecchetto** [comment]
Corriger dans 9d82ab5613ec5c71e4394253599d8b11feccdd7c et c0b372513a86c09028e5adce42a0d02a49848b53

Je ferme l'issue.

Merci encore wwark ;-D

**Comment by wwark** [comment]
Merci tout est ok pour moi !
