### ISSUE TITLE
Erreur avec la chaine Arte et la Chaine TF1

### ISSUE THREAD

**Issue by wwark** [SylvainCecchetto/plugin.video.catchuptvandmore#5]
Hello,

J'ai deux types d'erreur sur mon PC utilisant comme OS la Debian/Stretch.

Arte :
21:49:37.773 T:140585121942400  NOTICE: Previous line repeats 2 times.
21:49:37.773 T:140585121942400   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
21:49:52.894 T:140584087688960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'categories'
                                            Traceback (most recent call last):
                                              File "/home/****/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 276, in <module>
                                                common.plugin.run(common.plugin_name)
                                              File "/home/****/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/home/*****/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 234, in channel_entry
                                                return channel.channel_entry(params)
                                              File "/home/****/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/arte.py", line 39, in channel_entry
                                                return list_shows(params)
                                              File "/home/****/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 443, in inner_wrapper
                                                data = func(*args, **kwargs)
                                              File "/home/***/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/arte.py", line 63, in list_shows
                                                for category in json_parser['categories']:
                                            KeyError: 'categories'
                                            -->End of Python script error report<--
21:49:52.984 T:140585121942400   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.arte.arte&channel_module=channels.fr.arte&channel_name=arte&next=list_shows_1
21:49:52.985 T:140585121942400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.arte.arte&channel_module=channels.fr.arte&channel_name=arte&next=list_shows_1) failed

TF1 :
21:53:22.536 T:140584108668672   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute '_base'
                                            Traceback (most recent call last):
                                              File "/home/***/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 276, in <module>
                                                common.plugin.run(common.plugin_name)
                                              File "/home/***/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/home/***/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 231, in channel_entry
                                                channel_path)
                                              File "/home/***/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/tf1.py", line 24, in <module>
                                                from bs4 import BeautifulSoup as bs
                                              File "/home/***/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 30, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/home/***/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 311, in <module>
                                                from . import _html5lib
                                              File "/home/****/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py", line 57, in <module>
                                                class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
                                            AttributeError: 'module' object has no attribute '_base'
                                            -->End of Python script error report<--
21:53:22.563 T:140585121942400   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.fr.tf1&channel_name=tf1&next=list_shows_1
21:53:22.564 T:140585121942400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.fr.tf1&channel_name=tf1&next=list_shows_1) failed

D'avance merci,
Wark.

**Comment by SylvainCecchetto** [comment]
Bonjour wwark,

Tout d'abord merci de ton retour,

Concernant Arte j'ai un problème de clé actuellement, mais je suis en train de m'en occuper et je pense pourvoir mettre ça à jour ce soir ou demain.

Par contre j'ai n'ai pas de problème avec TF1 ... quelle version utilises-tu ?
On dirait un problème avec BeautifulSoup, tu as bien BeautifulSoup 4 d'installé dans ton Kodi ?

**Comment by wwark** [comment]
Bonjour,

Merci pour la prise en compte de ma demande.

Au niveau de mon kodi, c'est la version 4.3.2 de Leonard Richarson pour BeautifulSoup 4.
J'ai aussi BeautifulSoup d'installé en version 3.2.1.

Est-ce la bonne version ?

**Comment by SylvainCecchetto** [comment]
Pour BS4 la version 4.3.2 fonctionne normalement.

Est ce que tu aurais la possibilité de tester la version de la branche 'dev' ? : https://github.com/SylvainCecchetto/plugin.video.catchuptvandmore/archive/dev.zip

Au moins pour voir si TF1 fonctionne (pour Arte je suis dessus en ce moment ...)

**Comment by wwark** [comment]
J'ai toujours le même erreur 

22:20:57.236 T:140205444744960   ERROR: GetDirectory - Error getting
22:20:59.088 T:140202630706944   ERROR: Previous line repeats 6 times.
22:20:59.088 T:140202630706944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute '_base'
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 282, in <module>
                                                common.plugin.run(window_title)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 236, in channel_entry
                                                channel_path)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/tf1.py", line 24, in <module>
                                                from bs4 import BeautifulSoup as bs
                                              File "/home/wark/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 30, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/home/wark/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 311, in <module>
                                                from . import _html5lib
                                              File "/home/wark/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py", line 57, in <module>
                                                class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
                                            AttributeError: 'module' object has no attribute '_base'
                                            -->End of Python script error report<--
22:20:59.123 T:140206137609088   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.fr.tf1&channel_name=tf1&next=list_shows_1&window_title=TF1
22:20:59.123 T:140206137609088   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.fr.tf1&channel_name=tf1&next=list_shows_1&window_title=TF1) failed

**Comment by SylvainCecchetto** [comment]
Je viens de tester de mon coté et je n'ai aucun problème. J'ai vraiment l'impression que l'erreur vient de BS4 pourtant d'après ton log :-/

Est ce que tu pourrais essayer la chaine L'équipe stp. (Cette chaine utilise aussi BS4 donc si tu as la même message d'erreur je pense qu'on pourra être sûr que c'est BS4 qui a un problème).

Peut être peux-tu essayer de désinstaller BS4 et désinstaller Catch TV & More. Enfin tu re installes Catch TV & More depuis le fichier zip et normalement Kodi va re installer automatiquement BS4 depuis les dépôts officiels.

En espérant que ça fonctionne pour toi parce que je n'arrive pas à reproduire ce bug chez moi

**Comment by wwark** [comment]
ok. je test.

La trace en debug au cas où.

22:28:09.238 T:140206137609088   DEBUG: Keyboard: scancode: 0x40, sym: 0x0134, unicode: 0x0000, modifier: 0x100
22:28:09.238 T:140206137609088   DEBUG: OnKey: alt-leftalt (0x4f0d4) pressed, action is
22:28:14.304 T:140206137609088   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
22:28:20.165 T:140206137609088   DEBUG: ------ Window Init (Pointer.xml) ------
22:28:20.372 T:140204164245248   DEBUG: GetImageHash - unable to stat url /home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/media/channels/fr/france5_fanart.png
22:28:21.576 T:140206137609088   DEBUG: Previous line repeats 1 times.
22:28:21.576 T:140206137609088   DEBUG: ProcessMouse: trying mouse action leftclick
22:28:21.576 T:140206137609088   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.fr.tf1&channel_name=tf1&next=li
st_shows_1&window_title=TF1)
22:28:21.576 T:140206137609088   DEBUG:   ParentPath = [plugin://plugin.video.catchuptvandmore/]
22:28:21.583 T:140204164245248   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.catchuptvandmore] took 6 ms
22:28:21.583 T:140205444744960   DEBUG: StartScript - calling plugin Catch-up TV & More('plugin://plugin.video.catchuptvandmore/','33','?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.fr.tf
1&channel_name=tf1&next=list_shows_1&window_title=TF1')
22:28:21.583 T:140205417387776   DEBUG: Thread LanguageInvoker start, auto delete: false
22:28:21.583 T:140205417387776    INFO: initializing python engine.
22:28:21.583 T:140205417387776   DEBUG: CPythonInvoker(40, /home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py): start processing
22:28:21.614 T:140205417387776   DEBUG: -->Python Interpreter Initialized<--
22:28:21.614 T:140205417387776   DEBUG: CPythonInvoker(40, /home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the source file to load is "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py"
22:28:21.614 T:140205417387776   DEBUG: CPythonInvoker(40, /home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py): setting the Python path to /home/wark/.kodi/addons/plugin.video.catchuptvandmore:/home/wark/.kodi/addons/script.m
odule.beautifulsoup4/lib:/home/wark/.kodi/addons/script.module.requests/lib:/home/wark/.kodi/addons/script.module.simplejson/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib
-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
22:28:21.614 T:140205417387776   DEBUG: CPythonInvoker(40, /home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py): entering source directory /home/wark/.kodi/addons/plugin.video.catchuptvandmore
22:28:21.614 T:140205417387776   DEBUG: CPythonInvoker(40, /home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py): instantiating addon using automatically obtained id of "plugin.video.catchuptvandmore" dependent on version 2.25.
0 of the xbmc.python api
22:28:21.658 T:140205417387776   DEBUG: plugin.video.catchuptvandmore [v.0.1.2]: <Plugin ['plugin://plugin.video.catchuptvandmore/', '33', '?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.f
r.tf1&channel_name=tf1&next=list_shows_1&window_title=TF1']>
22:28:21.658 T:140205417387776   DEBUG: plugin.video.catchuptvandmore [v.0.1.2]: Actions: ['hide', 'list_channels', 'move', 'root', 'channel_entry']
22:28:21.658 T:140205417387776   DEBUG: plugin.video.catchuptvandmore [v.0.1.2]: Called action "channel_entry" with params "<Params {'channel_module': 'channels.fr.tf1', 'channel_country': 'fr', 'channel_id': 'channels.fr.tf1.tf1', 'next
': 'list_shows_1', 'channel_name': 'tf1', 'action': 'channel_entry', 'window_title': 'TF1'}>"
22:28:21.754 T:140205417387776   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute '_base'
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 282, in <module>
                                                common.plugin.run(window_title)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 236, in channel_entry
                                                channel_path)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/tf1.py", line 24, in <module>
                                                from bs4 import BeautifulSoup as bs
                                              File "/home/wark/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 30, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/home/wark/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 311, in <module>
                                                from . import _html5lib
                                              File "/home/wark/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py", line 57, in <module>
                                                class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
                                            AttributeError: 'module' object has no attribute '_base'
                                            -->End of Python script error report<--
22:28:21.778 T:140205417387776    INFO: Python script stopped
22:28:21.778 T:140205417387776   DEBUG: Thread LanguageInvoker 140205417387776 terminating
22:28:21.784 T:140206137609088   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.fr.tf1&channel_name=tf1&next=list
_shows_1&window_title=TF1
22:28:21.784 T:140206137609088   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&channel_country=fr&channel_id=channels.fr.tf1.tf1&channel_module=channels.fr.tf1&channel_name=tf1&next=lis
t_shows_1&window_title=TF1) failed
22:28:21.784 T:140206137609088   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.catchuptvandmore/)

**Comment by wwark** [comment]
Malgré la suppression de l'addon et de BS4 et un arrêt de KODI et la réinstallation de l'addon, le problème persiste.

Je vais continuer à chercher pour voir si je trouve pas autre chose ...

**Comment by SylvainCecchetto** [comment]
Oh c'est chiant ça :-(

Bon courage dans tes recherches, je regarderai aussi de mon coté.

Si tu trouves quelque chose je suis preneur de ton avancé

PS : Je push un correctif préliminaire pour Arté ce soir sur la branche 'dev'

**Comment by wwark** [comment]
Merci ! Je confirme aussi que toutes les chaines utilisant BS4 ont le même problème. 
Je me demande si ma version de python n'est pas la cause. Python 2.7.13

**Comment by SylvainCecchetto** [comment]
Bon on va dire que le problème est identifié mais pas encore résolu !

Alors je ne veux pas dire de bêtise mais est ce que Kodi n'utilise pas son "propre" python ? (Je ne suis vraiment pas sûr de ce que je dis là ... à vérifier)

**Comment by wwark** [comment]
https://bugs.launchpad.net/ubuntu/+source/beautifulsoup4/+bug/1603299 
Ce bug a l'air de ressembler à mon cas.

**Comment by SylvainCecchetto** [comment]
Effectivement, un problème avec html5lib à priori ...

http://stackoverflow.com/questions/38447738/beautifulsoup-html5lib-module-object-has-no-attribute-base

**Comment by wwark** [comment]
J'ai remplacé tous les valeurs "_base" par "base" dans le fichier /home/wark/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py et ça marche :) Je peux accéder aux chaines utilisant BS4.

J'ai un autre addon utilisant BS4 je vais voir si l'autre addon fonctionne avec cette modification.

**Comment by SylvainCecchetto** [comment]
Ben écoute si tu as pu résoudre ton problème avec cette astuce tant mieux. Si je ne dis pas de bêtise je crois que la team Kodi va prochainement mettre à jour BS4 sur le repo officiel, peut être que ce problème sera résolu ...

(Je viens de pusher la correction pour Arte)

**Comment by wwark** [comment]
Merci !
Test Arte OK.
